extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  memory_limiter:
    check_interval: 2s
    limit_mib: 400
    spike_limit_mib: 100
  resourcedetection:
    detectors: [env, system]
    timeout: 2s
    override: false
  batch:
    send_batch_size: 512
    timeout: 5s

exporters:
  debug:
    verbosity: basic
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: demo
    send_timestamps: true
    metric_expiration: 5m

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [prometheus, debug]
    logs:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [debug]
